services:
  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    environment:
      DISABLE_IPV6: "true"
    volumes:
      - "nginx-proxy-manager-data:/data"
      - "nginx-proxy-manager-letsencrypt-data:/etc/letsencrypt"
  caprover:
    image: "caprover/caprover:latest"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "caprover-captain:/captain"
    environment:
      ACCEPTED_TERMS: "true"
volumes:
  nginx-proxy-manager-data:
  nginx-proxy-manager-letsencrypt-data:
  caprover-captain:
