version: '3.8'
services:
	nginx-proxy-manager:
		image: 'jc21/nginx-proxy-manager:latest'
		restart: unless-stopped
		ports:
			- '80:80' # Public HTTP Port
			- '443:443' # Public HTTPS Port
			- '81:81' # Admin Web Port
		environment:
			DISABLE_IPV6: 'true'
		volumes:
			- ./data:/data
			- ./letsencrypt:/etc/letsencrypt
	dokku:
		image: dokku/dokku:0.34.4
		ports:
			- "3022:22"
			- "8080:80"
			- "8443:443"
		volumes:
			- "/var/lib/dokku:/mnt/dokku"
			- "/var/run/docker.sock:/var/run/docker.sock"
		environment:
			DOKKU_HOSTNAME: dokku.me
			DOKKU_HOST_ROOT: /var/lib/dokku/home/dokku
			DOKKU_LIB_HOST_ROOT: /var/lib/dokku/var/lib/dokku
		restart: unless-stopped
	portainer:
		image: "portainer_data:/data portainer/portainer-ce:latest"
		ports:
			- "8000:8000"
			- "9443:9443"
		volumes:
			- "/var/run/docker.sock:/var/run/docker.sock"
			- "portainer_data:/data portainer/portainer-ce:latest"
		restart: unless-stopped
volumes:
	portainer_data:
